### ISSUE TITLE
WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin)

### ISSUE THREAD

**Issue by greedyyy** [kodi-czsk/plugin.video.videacesky.cz#10]
uz som sa pytal v inom vlakne ale stale nemam riesenie. 
po update na android 6 mi neporehra ziadne video na videacesky. 
v logu je nasledujuce: 

10:54:25 T:18446744072975960368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f636f6e616e2d6a6f7264616e2d7363686c616e736b792d726563656e7a756a652d7562726f75736b792d6e612d68656d65726f696479&cp=76696465616365736b792e637a&
10:54:28 T:18446744072903981360  NOTICE: ["Initializing provider videacesky.cz with settings {'downloads': '', 'quality': '1'}"]
10:54:29 T:18446744072903981360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.videacesky.cz/default.py", line 142, in <module>
                                                VideaceskyXBMCContentProvider(videacesky.VideaceskyContentProvider(tmp_dir=xbmc.translatePath(**addon**.getAddonInfo('profile'))), settings, **addon**).run(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 71, in run
                                                return self.play({'url':params['play'],'info':params})
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.videacesky.cz/default.py", line 78, in play
                                                stream = self.resolve(item['url'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.videacesky.cz/default.py", line 135, in resolve
                                                return self.provider.resolve(item, select_cb=select_cb)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.videacesky.cz/resources/lib/videacesky.py", line 158, in resolve
                                                jsondata = re.sub(' +',' ','{%s' % playlist.group('jsondata').replace('file:','"file":').replace('label:','"label":').replace('kind:','"kind":').replace('default:','"default":').replace('true','"true"').replace('],',']'))+'}'
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
10:54:29 T:18446744073503148336   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f6379616e6964652d68617070696e6573732d726f7a686f646e757469&cp=76696465616365736b792e637a&]
10:54:31 T:18446744072947239216 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f6379616e6964652d68617070696e6573732d726f7a686f646e757469&cp=76696465616365736b792e637a&

**Comment by brozikcz** [comment]
Je problem stale aktualni?

**Comment by greedyyy** [comment]
dik, moze sa zavriet, uz je to nejaky ten piatok OK, zabudol som na to.
