### ISSUE TITLE
Náhodné nenačítání titulků

### ISSUE THREAD

**Issue by pschonmann** [kodi-czsk/plugin.video.videacesky.cz#13]
Ahoj, občas se stane, že se nezobrazí titulky. Když jsem se koukal do logů viděl jsem vše ok. Žádná chyba i titulky se stáhly. Po dohledání souboru z logu opravdu byly ve složce resolveru a seděli, nicméně kodi nebo doplněk je z nějakého důvodu nezobrazilo.

**Comment by brozikcz** [comment]
Dokazes to nejak nasimulovat? Me se to zatim stalo jen jednou a to pouzivam addon celkem casto.

**Comment by pschonmann** [comment]
Zkusím, poslední dobou jsem se vůbec skrz tenhle doplněk nekoukal. Updatuji Kodi na poslední verzi. Uvidíme. Je třeba zapnout debug, něco navíc aby jsi pak dohledal co doplněk dělá - nějaké tracování ?

**Comment by brozikcz** [comment]
Uz jsem to vcera fixnul :)

**Comment by pschonmann** [comment]
V  tom případě možno zavřít a updatovat v repo :)
