### ISSUE TITLE
Nefunguje

### ISSUE THREAD

**Issue by murray9310** [kodi-czsk/plugin.video.videacesky.cz#17]
Ahoj, maly problem, videa vubec nejdou prehravat, bylo by mozne s tim neco udelat? Dekuji mnohokrat, odvadite skvelou praci.

**Comment by jose1711** [comment]
to by malo byt vyriesene v https://github.com/kodi-czsk/plugin.video.videacesky.cz/pull/16, ale zatial to nik nechce mergnut

**Comment by murray9310** [comment]
Mne se prave od prichodu kodi 17 nechteji zobrazovat pravidelne titulky, obcas jo obcas ne, ale ted to uplne kleklo.

**Comment by brozikcz** [comment]
@murray9310 to je reseno tady: https://github.com/kodi-czsk/plugin.video.videacesky.cz/issues/13 je tu i pull request na to

**Comment by locki-cz** [comment]
když jsou ty titulky fixnuté půl roku proč to stále nefunguje? nějak to nepobírám :( mám poslední verzi 1.0.18

**Comment by murray9310** [comment]
Ahoj, 

kontaktoval jsem frajera, kterej programoval ty neschvaleny zmeny na githubu
a on mi poslal aktualizacni soubor, kterej funguje na androidu na maline 
proste vsude. Poslal bych ji , ale nechci to šířit bez jeho vědomí. Napiš 
mu, tady je jeho mail brozikcz@gmail.com.

Měj se

---------- Původní zpráva ----------
Od: locki-cz 
Datum: 28. 10. 2017 v 19:56:05
Předmět: Re: [kodi-czsk/plugin.video.videacesky.cz] Nefunguje (#17)


když jsou ty titulky fixnuté půl roku proč to stále nefunguje? nějak to 
nepobírám :( mám poslední verzi 1.0.18

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
(https://github.com/kodi-czsk/plugin.video.videacesky.cz/issues/17#issuecomment-340208698)
, or mute the thread

**Comment by locki-cz** [comment]
tak řešení je zde: http://www.xbmc-kodi.cz/prispevek-videacesky-cz?pid=32255#pid32255 stačí stáhnout fixnutý doplněk ...

**Comment by brozikcz** [comment]
Mergnuto.

**Comment by locki-cz** [comment]
Super!
