### ISSUE TITLE
viac videi

### ISSUE THREAD

**Issue by greedyyy** [kodi-czsk/plugin.video.videacesky.cz#23]
niektore videa maju playlist s viacerimi pokracovaniami 
kodi ponukne a prehra len prve, ostatne ignoduje.
napr https://videacesky.cz/video/the-graham-norton-show-tetovani-zive-ve-studiu.

inak nasiel som podobny web ako videacesky.cz, http://titulkomet.cz. neslo by tam  spravit doplnok?

**Comment by brozikcz** [comment]
Opraveno. Na odkazovany web se podivam.

**Comment by brozikcz** [comment]
Doplnek pro titulkomet: http://www.xbmc-kodi.cz/prispevek-titulkomet-cz

**Comment by jose1711** [comment]
super, ale preco na to nespravis rovno repo na githube?

**Comment by brozikcz** [comment]
repo uz je, jen neni PR do kodi repozitare

chci to nejdriv trosku otestovat...
