### ISSUE TITLE
viac videi - titulky len pri prvom

### ISSUE THREAD

**Issue by jose1711** [kodi-czsk/plugin.video.videacesky.cz#28]
po vybere *play all* pri vybere poloziek obsahujucich viacero videi sa titulky zobrazia len pri prvom videu. testovane na raspi (osmc) + arch linuxe

**Comment by brozikcz** [comment]
Fix: https://github.com/kodi-czsk/plugin.video.videacesky.cz/pull/29

Bohuzel netusim, jak vyresit pro Kodi < 16

**Comment by jose1711** [comment]
dik, to ma osobne velmr netrapi
