### ISSUE TITLE
Nejde prehravat videacesky.cz

### ISSUE THREAD

**Issue by pschonmann** [kodi-czsk/plugin.video.videacesky.cz#3]
Vyberu v pluginu posledni videa a zadne nejde prehravat.

```
23:23:25 T:8644  NOTICE: Thread LanguageInvoker start, auto delete: false
23:23:25 T:8644  NOTICE: -->Python Interpreter Initialized<--
23:23:26 T:8644  NOTICE: ["Initializing provider videacesky.cz with settings {'downloads': '', 'quality': '1'}"]
23:23:26 T:8644  NOTICE: ['No resolvables found!']
23:23:30 T:8644  NOTICE: <type 'NoneType'>
23:23:30 T:2864   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f6e61766f64792d646f6b756d656e74792d706f6b7573792f67616d652d6d616b6572732d746f6f6c6b69742d352d6e656a6c6570736963682d6865726e6963682d64657369676e752d7a2d726f6b752d32303135&cp=76696465616365736b792e637a&]
23:23:30 T:2864  NOTICE: CDVDPlayer::CloseFile()
```

**Comment by ghost** [comment]
opravil jsem prehravani pokud jde o jedno video (ceka v pull requestu). v pripade, ze je vice videi v clanku tak se prehraje jenom prvni.

**Comment by JimmyS83** [comment]
Ahoj, stejna chyba, stejny log :(

> 16:43:44 390.218994 T:1611056192  NOTICE: ["Initializing provider videacesky.cz with settings {'downloads': '', 'quality': '1'}"]
> 16:43:44 390.282776 T:1611056192  NOTICE: ['No resolvables found!']
> 16:43:46 392.273285 T:1968119808   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f736b6563652f6b65792d612d7065656c652d6f747261766e792d74656c656d61726b6574696e67&cp=76696465616365736b792e637a&]

**Comment by greedyyy** [comment]
neviem co som spravil ale plugin mi prestal chodit na androide, 
na linuxe aj win ide. 

`

> 14:47:52 T:18446744072906082608  NOTICE: ["Initializing provider videacesky.cz with settings {'downloads': '', 'quality': '1'}"]
> 14:47:53 T:18446744072907127088  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
> 14:47:53 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f686c75626f6b792d7665736d69722d36392d6465726176652d6d616e7a656c73747669&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f7665726974617369756d2d696c757a652d707261766479&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f657175616c732d74687265652d62616e616e6f76612d6e6f636e692d6d757261&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f73747564696f2d632d736b6f6c612d666c6972746f76616e69&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f686c75626f6b792d7665736d69722d36392d67616c616b7469636b652d62726174727374766f2d636173742d332d&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072925669680 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f626f6172642d776974682d6c6966652d74616d6d616e792d68616c6c&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072946714928 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f636f6e616e2d7a6e6f76752d73686c6564616e692d732d63686f626f746e6963692d73616d75656c&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072977131824 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f68756465626e692d6b6c656e6f74792d32302d73746f6c6574692d646f6c6c792d706172746f6e2d692d77696c6c2d616c776179732d6c6f76652d796f75&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f636f2d64656c616c2d74686f722d626568656d2d6f6263616e736b652d76616c6b79&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072925669680 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f67616d652d6d616b6572732d746f6f6c6b69742d6c6576656c2d64657369676e2d6d6574726f696476616e6969&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072946714928 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f66616c6c6f75742d6e756b612d627265616b2d6e6f76692d73706f6a656e6369&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f776f756c642d692d6c69652d746f2d796f752d7a64612d73652d7068696c752d7475666e656c6c6f76692d6f70616b6f76616e652d62697a61726e692d73656e&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072977131824 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f62657a6e792d64656e2d6e612d6672616e636f757a736b656d2d7572616465&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072977131824 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f736d61727465722d65766572792d6461792d7465746f76616e692d76652d7a706f6d616c656e656d2d7a6162657275&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072977131824 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f7468652d67726168616d2d6e6f72746f6e2d73686f772d63656c6562726974792d762d726f6c692d696d697461746f7275&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072946714928 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f7a617a7261636e792d63686c617065632d646f73746176612d6c756b72617469766e692d6e616269646b792d7072616365&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072925669680 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f6a696d6d792d6b696d6d656c2d6c6976652d686c6564612d73652d6d616c612d6e6576657374612d33&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072925669680 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f7468652d6c6174652d73686f772d776974682d7374657068656e2d636f6c626572742d627279616e2d6372616e73746f6e2d752d7374657068656e612d636f6c6265727461&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072946714928 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f616e6772792d766964656f2d67616d652d6e6572642d7365616d616e&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072977131824 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f6b6f6e7665727a6163652d732d6d6f752d64766f756c65746f752d657069736f64612d32&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072977131824 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f73616e2d73656261737469616e2d6576726f70736b652d6d6573746f2d6b756c747572792d32303136&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f6c6173742d7765656b2d746f6e696768742d6a6f686e6e792d73696c616b&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072925669680 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f6379616e6964652d68617070696e6573732d64656e2d686173696375&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072977131824 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f7461626c65746f702d73657269662d7a2d6e6f7474696e6768616d75&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f666c6972746f76616e692d732d6b6174652d6d61726f75&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f676172792d73617665732d7468652d6772617665796172642d7072766e692d64656e2d762d7072616369&cp=76696465616365736b792e637a&
> 14:47:53 T:18446744072925669680 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f76652d7a6b72617463652d6e656d6f686c2d6a73656d2d75736e6f7574&cp=76696465616365736b792e637a&
> 14:47:56 T:18446744072884058416  NOTICE: ["Initializing provider videacesky.cz with settings {'downloads': '', 'quality': '1'}"]
> 14:47:58 T:18446744072884058416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.AttributeError'>
>                                             Error Contents: 'NoneType' object has no attribute 'group'
>                                             Traceback (most recent call last):
>                                               File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.videacesky.cz/default.py", line 142, in <module>
>                                                 VideaceskyXBMCContentProvider(videacesky.VideaceskyContentProvider(tmp_dir=xbmc.translatePath(**addon**.getAddonInfo('profile'))), settings, **addon**).run(params)
>                                               File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 71, in run
>                                                 return self.play({'url':params['play'],'info':params})
>                                               File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.videacesky.cz/default.py", line 78, in play
>                                                 stream = self.resolve(item['url'])
>                                               File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.videacesky.cz/default.py", line 135, in resolve
>                                                 return self.provider.resolve(item, select_cb=select_cb)
>                                               File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.videacesky.cz/resources/lib/videacesky.py", line 158, in resolve
>                                                 jsondata = re.sub(' +',' ','{%s' % playlist.group('jsondata').replace('file:','"file":').replace('label:','"label":').replace('kind:','"kind":').replace('default:','"default":').replace('true','"true"').replace('],',']'))+'}'
>                                             AttributeError: 'NoneType' object has no attribute 'group'
>                                             -->End of Python script error report<--
> 14:47:58 T:18446744073500887344   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f7461626c65746f702d73657269662d7a2d6e6f7474696e6768616d75&cp=76696465616365736b792e637a&]
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f686c75626f6b792d7665736d69722d36392d6465726176652d6d616e7a656c73747669&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f7665726974617369756d2d696c757a652d707261766479&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f657175616c732d74687265652d62616e616e6f76612d6e6f636e692d6d757261&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f73747564696f2d632d736b6f6c612d666c6972746f76616e69&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f686c75626f6b792d7665736d69722d36392d67616c616b7469636b652d62726174727374766f2d636173742d332d&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f626f6172642d776974682d6c6966652d74616d6d616e792d68616c6c&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f636f6e616e2d7a6e6f76752d73686c6564616e692d732d63686f626f746e6963692d73616d75656c&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f68756465626e692d6b6c656e6f74792d32302d73746f6c6574692d646f6c6c792d706172746f6e2d692d77696c6c2d616c776179732d6c6f76652d796f75&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f636f2d64656c616c2d74686f722d626568656d2d6f6263616e736b652d76616c6b79&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f67616d652d6d616b6572732d746f6f6c6b69742d6c6576656c2d64657369676e2d6d6574726f696476616e6969&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f66616c6c6f75742d6e756b612d627265616b2d6e6f76692d73706f6a656e6369&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f776f756c642d692d6c69652d746f2d796f752d7a64612d73652d7068696c752d7475666e656c6c6f76692d6f70616b6f76616e652d62697a61726e692d73656e&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f62657a6e792d64656e2d6e612d6672616e636f757a736b656d2d7572616465&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f736d61727465722d65766572792d6461792d7465746f76616e692d76652d7a706f6d616c656e656d2d7a6162657275&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f7468652d67726168616d2d6e6f72746f6e2d73686f772d63656c6562726974792d762d726f6c692d696d697461746f7275&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f7a617a7261636e792d63686c617065632d646f73746176612d6c756b72617469766e692d6e616269646b792d7072616365&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f6a696d6d792d6b696d6d656c2d6c6976652d686c6564612d73652d6d616c612d6e6576657374612d33&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f7468652d6c6174652d73686f772d776974682d7374657068656e2d636f6c626572742d627279616e2d6372616e73746f6e2d752d7374657068656e612d636f6c6265727461&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f616e6772792d766964656f2d67616d652d6e6572642d7365616d616e&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f6b6f6e7665727a6163652d732d6d6f752d64766f756c65746f752d657069736f64612d32&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f73616e2d73656261737469616e2d6576726f70736b652d6d6573746f2d6b756c747572792d32303136&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f6c6173742d7765656b2d746f6e696768742d6a6f686e6e792d73696c616b&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f6379616e6964652d68617070696e6573732d64656e2d686173696375&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f7461626c65746f702d73657269662d7a2d6e6f7474696e6768616d75&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f666c6972746f76616e692d732d6b6174652d6d61726f75&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072938584368 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f676172792d73617665732d7468652d6772617665796172642d7072766e692d64656e2d762d7072616369&cp=76696465616365736b792e637a&
> 14:48:00 T:18446744072977131824 WARNING: static XFILE::IFile\* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.videacesky.cz/?play=687474703a2f2f7777772e76696465616365736b792e637a2f766964656f2f76652d7a6b72617463652d6e656d6f686c2d6a73656d2d75736e6f7574&cp=76696465616365736b792e637a&
