### ISSUE TITLE
Nefunkcne prehravanie vacsiny videi

### ISSUE THREAD

**Issue by mino182** [kodi-czsk/plugin.video.videacesky.cz#32]
Cauko, objavil sa problem s prehravanim videi. V sekcii " najnovsie videa" sa vacsina videi neda spustit. V sekcii "The Graham Norton Show" sa nespusti ziadne, aj ked predtym islo (je oznacene ako videne). Diky.

Android 8.1, SPMC 16.7,  videacesky.cz v1.0.24

**Comment by brozikcz** [comment]
Ahoj,

muzes zkusit tuto verzi: [plugin.video.videacesky.cz.zip](https://github.com/kodi-czsk/plugin.video.videacesky.cz/files/4015403/plugin.video.videacesky.cz.zip)

Je v ni pouzit module youtube-dl, protoze uz me nebavi porad resit zmeny okolo youtube videii.
Nejsem si ale jisty, jak bude fungovat na starych verzich kodi.

**Comment by murray9310** [comment]
Super, funguje, díky.
