### ISSUE TITLE
Některá videa nefungují

### ISSUE THREAD

**Issue by murray9310** [kodi-czsk/plugin.video.videacesky.cz#33]
Ahoj, bylo by možné mrknout na doplněk? Některá videa přestala fungovat např. https://videacesky.cz/video/vox-rok-2019-v-sesti-minutach, https://videacesky.cz/video/would-i-lie-to-you-byl-ian-podezrely-z-vrazdy-boji-se-letani-nebo-vlastni-jestery, https://videacesky.cz/video/diablo-iv, ale je jich více.
Díky

**Comment by brozikcz** [comment]
https://github.com/kodi-czsk/plugin.video.videacesky.cz/issues/32

**Comment by murray9310** [comment]
Moje chyba, všimnul jsem si pozdě.
