### ISSUE TITLE
Doplnek

### ISSUE THREAD

**Issue by jindar7** [kodi-czsk/plugin.video.videacesky.cz#38]
Zdravím,

aktualizoval se mi KODI na verzi 20, doplněk bohužel nelze nainstalovat z důvodu chybějícího modulu "youtube-dl Control Minimum: 21.417.10". Existuje nějaký způsob jak tento modul nainstalovat do KODI verze 20? Děkuji mnohokrát za odpověď.

Zdraví
jindar7

**Comment by brozikcz** [comment]
Ahoj, zkus tady https://www.xbmc-kodi.cz/prispevek-videacesky-cz?pid=106727#pid106727

**Comment by jindar7** [comment]
Zdravím,

mockrát děkuji za tip, vše zprovozněno pod KODI 20 a funguje.

Ještě jednou děkuji
jindar7
